# This docker-compose should be user for development purposes only.
version: '3'
services:
  web:
    image: ${DOCKER_IMAGE_NAME-spree}
    build: .
    command: ["./wait-for", "db:5432", "--", "bundle", "exec", "puma", "-C", "config/puma.rb"] # Normal run
    # command: ["./wait-for", "db:5432", "--", "bundle", "exec", "rdebug-ide", "--host", "0.0.0.0", "--port", "1234", "--", "bin/bundle", "exec", "puma", "-C", "config/puma.rb"] # VSCode debug
    # This is a chain of commands.
    #   'wait-for db:5432' is a shell script that waits for database to be ready.
    #   '--' this chains a command when the last finishes
    #   'bundle exec rdebug-ide --host 0.0.0.0 --port 1234' This starts ruby-debug-ide, waiting to vscode to connect
    #   'bin/bundle exec puma -C config/puma.rb' This is the command that will be run when vscode connect
    volumes:
      - .:/myapp:cached
    ports:
      - "3000:3000"
      - "1234:1234"
      - "26162:26162"
    depends_on:
      - db
    environment:
      WEB_CONCURRENCY: 0
      DB_HOST: db
      DB_PASS: postgres
      DB_USER: postgres
      REDIS_URL: redis://redis:6379/0
      WEBPACKER_DEV_SERVER_HOST: yarn
      WEBPACKER_DEV_SERVER_PORT: 3001
      WEBPACKER_DEV_SERVER_PUBLIC: yarn:3001
    container_name: 'web' # Criar alias para debuggar usando o pry
    tty: true # Debuggar usando o pry
    stdin_open: true # Debuggar usando o pry
  db:
    image: postgres:12-alpine
    volumes:
      - ./tmp/db:/var/lib/postgresql/data:cached
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'