  # This docker-compose should be user for development purposes only.
  version: '3'
  services:
    web:
      image: ${DOCKER_IMAGE_NAME-manutencao}
      build: .
      command: ["./wait-for", "db:5432", "--", "bundle", "exec", "puma", "-C", "config/puma.rb"] # Normal run
      # command: ["./wait-for", "db:5432", "--", "bundle", "exec", "rdebug-ide", "--host", "0.0.0.0", "--port", "1234", "--", "bin/bundle", "exec", "puma", "-C", "config/puma.rb"] # VSCode debug
      # This is a chain of commands.
      #   'wait-for db:5432' is a shell script that waits for database to be ready.
      #   '--' this chains a command when the last finishes
      #   'bundle exec rdebug-ide --host 0.0.0.0 --port 1234' This starts ruby-debug-ide, waiting to vscode to connect
      #   'bin/bundle exec puma -C config/puma.rb' This is the command that will be run when vscode connect
      
      container_name: 'web' # Criar alias para o container para dar o attach depois

      volumes:
        - .:/myapp:cached
      ports:
        - "3000:3000"
        - "1234:1234"
        - "26162:26162"
      depends_on:
        - db
        # - redis
    #### COMMENT THIS NEXT LINE IF YOU DON'T USE YARN (any app made before 2019.2) ###
        # - yarn
      environment:
        WEB_CONCURRENCY: 0
        DEBUG_ASSETS: 'false'
        DB_HOST: db
        DB_PASS: postgres
        DB_USER: postgres
        # REDIS_URL: redis://redis:6379/0
        # WEBPACKER_DEV_SERVER_HOST: yarn
        # WEBPACKER_DEV_SERVER_PORT: 3001
        # WEBPACKER_DEV_SERVER_PUBLIC: yarn:3001
      
      # Debuggar usando o pry
      # Adicionar esses dois comandos
      tty: true
      stdin_open: true
      # -----------------------------

    # sidekiq:
    #   image: ${DOCKER_IMAGE_NAME-manutencao}
    #   command: ["./wait-for", "db:5432", "--", "bundle", "exec", "sidekiq", "-c", "6", "-q", "default", "-q", "mailers", "-q", "push_notifications"]
    #   volumes:
    #     - .:/myapp:cached
    #   depends_on:
    #     - db
    #     - redis
    #   environment:
    #     DB_HOST: db
    #     DB_PASS: postgres
    #     DB_USER: postgres
    #     REDIS_URL: redis://redis:6379/0
    #### COMMENT THIS ENTIRE NEXT BLOCK IF YOU DON'T USE YARN (any app made before 2019.2) ###
    # yarn:
    #   image: ${DOCKER_IMAGE_NAME-manutencao}
    #   command: ["yarn", "dev-start"]
    #   volumes:
    #     - .:/myapp:cached
    #   ports:
    #     - "3001:3001"
    #   environment:
    #     WEBPACKER_DEV_SERVER_HOST: yarn
    #     WEBPACKER_DEV_SERVER_PORT: 3001
    #     WEBPACKER_DEV_SERVER_PUBLIC: yarn:3001
    db:
      image: postgres:12-alpine
      volumes:
        - ./tmp/db:/var/lib/postgresql/data:cached
      environment:
        POSTGRES_PASSWORD: postgres
      ports:
        - '5432:5432'
    # redis:
    #   image: redis:alpine